version: '3.3'
services:
  opsli-boot:
    build: ./
    restart: on-failure
    container_name: opsli-boot
    image: opsli-boot
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    command:
      - -Xmx2048m
      - -Xms2048m
      - -XX:+UseG1GC
      - -XX:MaxGCPauseMillis=200
      - --spring.profiles.active=dev
    ports:
      - "8080:8080"